import { mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { resolve, join } from "node:path";
const root = resolve(import.meta.dirname, "../.."),
  temporary = await mkdtemp(join(tmpdir(), "docket-types-"));
try {
  const result = Bun.spawnSync(
    [
      resolve(root, "web/node_modules/.bin/tsc"),
      "--declaration",
      "--emitDeclarationOnly",
      "--strict",
      "--target",
      "ES2022",
      "--module",
      "ESNext",
      "--moduleResolution",
      "Bundler",
      "--lib",
      "DOM,ES2022",
      "--outDir",
      temporary,
      resolve(root, "packages/plugin-sdk/src/index.ts"),
    ],
    { cwd: root, stdout: "pipe", stderr: "pipe" },
  );
  if (result.exitCode !== 0)
    throw Error(
      new TextDecoder().decode(result.stdout) +
        new TextDecoder().decode(result.stderr),
    );
  const names = [
    "contracts.d.ts",
    ...(await readdir(temporary))
      .filter(
        (name) =>
          name.endsWith(".d.ts") &&
          !["contracts.d.ts", "index.d.ts"].includes(name),
      )
      .sort(),
  ];
  const text =
    "// Generated by web/scripts/generate-plugin-sdk.ts. Do not edit.\n" +
    (
      await Promise.all(
        names.map(async (name) =>
          (await readFile(join(temporary, name), "utf8"))
            .replace(/^import .*?;\n/gm, "")
            .replace(/^export \{\};\n/gm, ""),
        ),
      )
    ).join("\n");
  const target = resolve(root, "docs/plugin-sdk.d.ts");
  if (process.argv.includes("--check")) {
    if ((await readFile(target, "utf8")) !== text)
      throw Error(
        "Public declarations drifted. Run bun web/scripts/generate-plugin-sdk.ts.",
      );
  } else await writeFile(target, text);
  console.log("Public declarations are reproducible.");
} finally {
  await rm(temporary, { recursive: true, force: true });
}
