// Generated by web/scripts/generate-plugin-sdk.ts. Do not edit.
/** Wire types shared by the Docket host and sandboxed plugin frames. */
export interface TaskWait {
    id: string;
    kind: string;
    reason: string;
    reference?: string;
    since: string;
    actor?: string;
}
export type Wait = TaskWait;
export interface TaskReference {
    id: string;
    kind: string;
    url: string;
    title?: string;
    added_at: string;
    added_by?: string;
    resolver_id?: string;
    resolver_generation?: string;
}
export interface BoardTask {
    id: string;
    title: string;
    status: string;
    project?: string;
    labels: string[];
    assignee?: string;
    wait?: TaskWait;
    references: TaskReference[];
    active_sessions: unknown[];
    sessions?: unknown[];
    created_at: string;
    updated_at: string;
    resource_count: number;
    widget_summaries?: WidgetSummary[];
    widget_revision?: string;
}
export type WidgetLocation = "board" | "activity";
/** Capabilities a frame may request through the host bridge. */
export type PluginCapability = "task.read" | "task.comment" | "task.move" | "service.fetch" | "service.stream" | "open.external";
/** A ledger widget type. `entry` is the frame opened from the activity timeline. */
export interface PluginWidgetDeclaration {
    type: string;
    title: string;
    entry?: string;
    slots: WidgetLocation[];
}
/** A task detail panel or workspace page rendered as a sandboxed frame. */
export interface PluginViewDeclaration {
    id: string;
    title: string;
    entry: string;
}
/** @deprecated Retired build-time card declaration; read `widgets` instead. */
export interface PluginCardDeclaration {
    type: string;
    title: string;
    locations?: WidgetLocation[];
}
export interface PluginReferenceResolverDeclaration {
    id: string;
    pattern: string;
    kinds?: string[];
    /** Service path answering POST {workspace, task_id, reference} with a ResolvedReference. */
    endpoint?: string;
}
export interface PluginMetadata {
    name: string;
    version: string;
    api_version?: number;
    cards?: PluginCardDeclaration[];
    reference_resolvers: PluginReferenceResolverDeclaration[];
    service_base?: string;
    widgets?: PluginWidgetDeclaration[];
    panels?: PluginViewDeclaration[];
    pages?: PluginViewDeclaration[];
    capabilities?: PluginCapability[];
    /** `/plugin-ui/<name>/<hash>`; changes whenever the plugin's ui.dir changes. */
    ui_base?: string;
}
export interface ResolvedReference {
    label: string;
    icon?: string;
    meta?: Record<string, string>;
    href?: string;
}
export type PluginConfigFieldType = "string" | "number" | "boolean" | "list" | "map";
export interface PluginConfigField {
    type: PluginConfigFieldType;
    required?: boolean;
    default?: unknown;
    enum?: unknown[];
    secret?: boolean;
    description?: string;
}
export interface PluginConfigSchemas {
    instance?: Record<string, PluginConfigField>;
    workspace?: Record<string, PluginConfigField>;
    status?: Record<string, PluginConfigField>;
}
export type WidgetPriority = "attention" | "error" | "active" | "history";
export type WidgetTone = "neutral" | "positive" | "warning" | "danger" | "info";
export interface WidgetReference {
    kind: string;
    url: string;
    title: string;
}
export interface WidgetFallback {
    label: string;
    status_label: string;
    summary?: string;
    priority: WidgetPriority;
    started_at?: string;
    ended_at?: string;
    references?: WidgetReference[];
}
export interface WidgetRecordV1 {
    version: 1;
    widget_type: string;
    instance_id: string;
    task_id: string;
    created_at: string;
    revision: number;
    phase: "created" | "finalised";
    fallback: WidgetFallback;
}
export interface WidgetSummary extends Omit<WidgetRecordV1, "fallback"> {
    fallback: Pick<WidgetFallback, "label" | "status_label" | "priority"> & {
        references?: WidgetReference[];
    };
}
export interface WidgetIdentity {
    workspace: string;
    taskId: string;
    widgetType: string;
    instanceId: string;
}
export interface WidgetPreferences {
    theme: "light" | "dark";
    density: "compact" | "comfortable";
    reducedMotion: boolean;
}
export interface WidgetData {
    version: number;
    revision: number;
    value: unknown;
}
export interface WidgetFreshness {
    connection: string;
    receivedAt?: number;
    expiresAt?: number;
    stale: boolean;
    rehydrating: boolean;
    lastActivityAt?: string;
}
export interface WidgetRow {
    key: string;
    order: number;
    role: "text" | "step" | "code" | "reference";
    label: string;
    text?: string;
    reference?: WidgetReference;
}
/**
 * Declarative widget view. Hosts render it without running plugin code; a
 * live preview publishes it as `data.value.presentation`.
 */
export interface WidgetPresentation {
    label: string;
    status: {
        text: string;
        tone: WidgetTone;
    };
    terminal: boolean;
    priority: WidgetPriority;
    action?: string;
    notice?: {
        text: string;
        tone: WidgetTone;
    };
    summary?: string;
    rows?: WidgetRow[];
    references?: WidgetReference[];
    startedAt?: string;
    endedAt?: string;
}
export interface WidgetLivePayload {
    widget_version: 1;
    revision: number;
    data: {
        version: number;
        value: unknown;
    };
    last_activity_at?: string;
}
export interface LivePayload {
    kind: string;
    task?: string;
    session?: string;
    payload: unknown;
    ttl_ms: number;
}

/** Rejection raised by bridge calls; `code` is stable, `message` is advisory. */
export declare class BridgeError extends Error {
    readonly code: FrameErrorCode;
    constructor(code: FrameErrorCode, message?: string);
}
export interface StreamHandlers {
    message(data: string, name: string): void;
    open?(): void;
    error?(): void;
}
export interface Subscription {
    close(): void;
}
export interface DocketFrame {
    /** Latest context from the host; replaced on every update. */
    readonly context: FrameContext;
    /** Called with each new context, including the initial one. */
    onUpdate(listener: (context: FrameContext) => void): () => void;
    call<M extends FrameMethod>(method: M, params: FrameMethods[M]["params"]): Promise<FrameMethods[M]["result"]>;
    /** Fetch a path from this plugin's own service (`/plugins/<name>/<path>`). */
    fetch(path: string, init?: Omit<ServiceRequest, "path">): Promise<ServiceResponse>;
    /** Fetch and parse JSON from this plugin's service; throws on non-2xx. */
    json<T = unknown>(path: string, init?: Omit<ServiceRequest, "path">): Promise<T>;
    /** Server-sent events from this plugin's service, relayed by the host. */
    stream(path: string, handlers: StreamHandlers): Subscription;
    /** Persist a small JSON value in the host; returned as `context.state` after reloads. */
    setState(value: unknown): Promise<void>;
    readTask(taskId?: string): Promise<unknown>;
    comment(text: string, taskId?: string): Promise<unknown>;
    moveTask(status: string, taskId?: string): Promise<unknown>;
    navigate(path: string): Promise<void>;
    openExternal(url: string): Promise<boolean>;
}
/**
 * Connect to the Docket host. Resolves once the host sends `init`. Applies
 * theme tokens to `document.documentElement` and reports the document height
 * so the host can size the frame; pass `{autoResize: false}` to size manually.
 */
export declare function connect(options?: {
    autoResize?: boolean;
    applyTheme?: boolean;
}): Promise<DocketFrame>;

/**
 * Host ↔ frame protocol. Every message carries `docket: PROTOCOL_VERSION`.
 * Frames run with an opaque origin, so both sides authenticate by
 * `event.source`, never by `event.origin`.
 */
export declare const PROTOCOL_VERSION = 1;
export type FrameViewKind = "widget" | "panel" | "page";
export interface FrameWidget {
    identity: WidgetIdentity;
    record: WidgetRecordV1;
    /** Latest live preview, when the widget is still running. */
    data?: WidgetData;
    freshness?: WidgetFreshness;
    presentation: WidgetPresentation;
}
export interface FrameTheme {
    scheme: "light" | "dark";
    /** CSS custom properties (`--docket-widget-*`) to apply to the frame root. */
    tokens: Record<string, string>;
}
export interface FrameContext {
    plugin: string;
    workspace: string;
    view: {
        kind: FrameViewKind;
        id: string;
    };
    /** Present for task-scoped views when the plugin holds `task.read`. */
    task?: BoardTask;
    taskId?: string;
    widget?: FrameWidget;
    capabilities: PluginCapability[];
    preferences: WidgetPreferences;
    theme: FrameTheme;
    /** Host-held state saved by `state.set`; survives frame reloads. */
    state: unknown;
}
export interface ServiceRequest {
    path: string;
    method?: string;
    headers?: Record<string, string>;
    body?: string;
}
export interface ServiceResponse {
    status: number;
    headers: Record<string, string>;
    body: string;
}
/** Request methods, their params and results. */
export interface FrameMethods {
    "task.read": {
        params: {
            taskId?: string;
        };
        result: unknown;
    };
    "task.comment": {
        params: {
            taskId?: string;
            text: string;
        };
        result: unknown;
    };
    "task.move": {
        params: {
            taskId?: string;
            status: string;
        };
        result: unknown;
    };
    "service.fetch": {
        params: ServiceRequest;
        result: ServiceResponse;
    };
    "service.stream": {
        params: {
            path: string;
        };
        result: {
            stream: string;
        };
    };
    "stream.close": {
        params: {
            stream: string;
        };
        result: null;
    };
    navigate: {
        params: {
            path: string;
        };
        result: null;
    };
    "open.external": {
        params: {
            url: string;
        };
        result: {
            opened: boolean;
        };
    };
    "state.set": {
        params: {
            value: unknown;
        };
        result: null;
    };
}
export type FrameMethod = keyof FrameMethods;
export type FrameErrorCode = "capability_denied" | "invalid_request" | "unknown_method" | "too_many_requests" | "timeout" | "request_failed" | "cancelled";
export type HostMessage = {
    docket: 1;
    type: "init";
    context: FrameContext;
} | {
    docket: 1;
    type: "update";
    context: FrameContext;
} | {
    docket: 1;
    type: "response";
    id: string;
    ok: true;
    value: unknown;
} | {
    docket: 1;
    type: "response";
    id: string;
    ok: false;
    error: FrameErrorCode;
    message?: string;
} | {
    docket: 1;
    type: "stream";
    stream: string;
    event: "open" | "message" | "error" | "closed";
    name?: string;
    data?: string;
};
export type FrameMessage = {
    docket: 1;
    type: "ready";
} | {
    docket: 1;
    type: "resize";
    height: number;
} | {
    docket: 1;
    type: "request";
    id: string;
    method: FrameMethod;
    params: unknown;
};
export declare function isFrameMessage(value: unknown): value is FrameMessage;
export declare function isHostMessage(value: unknown): value is HostMessage;

/**
 * Theme tokens sent to frames as CSS custom properties. They mirror
 * tokens.css (checked by web/tests/plugin-bridge.test.ts); frames get the
 * resolved values because they cannot load Docket's stylesheet.
 */
export declare const LIGHT_TOKENS: Readonly<Record<string, string>>;
/** Only the tokens that differ from light. */
export declare const DARK_TOKENS: Readonly<Record<string, string>>;
export declare function themeTokens(scheme: "light" | "dark", density?: "compact" | "comfortable"): Record<string, string>;

export declare const WIDGET_BUDGETS: Readonly<{
    previewBytes: 16384;
    recordBytes: 8192;
    detailBytes: 65536;
    cacheEntries: 2048;
    cacheBytes: number;
    resolverEntries: 512;
    timeoutMS: 5000;
    renderMS: 1000;
    activityMounts: 20;
}>;
export declare const safeInteger: (value: unknown) => value is number;
export declare function jsonBytes(value: unknown): number;
export declare function validWidgetPayload(value: unknown): value is WidgetLivePayload;
export declare function validWidgetRecord(value: unknown, workspace: string): value is WidgetRecordV1;
export declare function widgetLive(identity: WidgetIdentity, payload: WidgetLivePayload, ttl_ms?: number): LivePayload;
export declare function serviceBase(name: string, path?: string): string | undefined;
/** External HTTPS is allowed for resources, never for task/session destinations. */
export declare function safeHref(ref: WidgetReference, identity: WidgetIdentity): string | null;
export declare function boundedPresentation(value: WidgetPresentation, expanded?: boolean): WidgetPresentation;
